### ISSUE TITLE
Suggestion: several meetings match

### ISSUE THREAD

**Issue by joacimmelin** [punktniklas/NiKom#118] opened 2018-10-27 14:46 UTC
If I want to go to a certain meeting in NiKom, I simply write: 

(Se) tiden --> Gå <meeting name>

If there is more than one meeting that is named "meeting name", I will simply be sent to the first one of the two. 

Instead, I would like NiKom to work like this:

(Se) tiden --> Gå Fidonet 

Flera matchningar - välj en av dessa: 

1. FidoNet FN_SYSOP
2. FidoNet LINUX
3. FidoNet FIDONEWS
4. FidoNet BBS_ADS
5. FidoNet BINKD
6. FidoNet FIDOTEST
7. FidoNet BBS_PROMOTION
8. FidoNet FIDOGAZETTE
9. FidoNet UTF-8

Välj möte: 5

Du befinner dig i FidoNet BINKD.
Det finns texter numrerade från 2 till 1897.
Du har 1896 olästa texter.

(Läsa) nästa text -->

**Comment by punktniklas** [comment] 2018-10-27 15:07
This is a duplicate of issue #54

**Closed by punktniklas** 2018-10-27 15:07 UTC
Labels: duplicate
